const mongoose = require('mongoose')
const supertest = require('supertest')
const helper = require('./test_helper')
const app = require('../app')
const api = supertest(app)
const Item = require('../models/item')
const bcrypt = require('bcrypt')
const User = require('../models/user')